// SPDX-License-Identifier: Zlib
// Copyright (C) 2024, Voxelius Contributors
#pragma once
#include <array>
#include <entt/entity/entity.hpp>
#include <game/shared/const.hh>
#include <game/shared/voxel.hh>

enum class ChunkType : std::uint16_t {
    Generic     = 0x0000, // Don't make assumptions
    Generated   = 0x0001, // Generated by worldgen
    Inhabited   = 0x0002, // Loaded from a save file
};

using VoxelStorage = std::array<Voxel, CHUNK_VOLUME>;
using LightStorage = std::array<std::int8_t, CHUNK_VOLUME>;

class Chunk final {
public:
    ChunkType type {};
    entt::entity entity {};
    VoxelStorage voxels {};

public:
    static Chunk *create(ChunkType type);
    static Chunk *create(ChunkType type, entt::entity entity);
    static void destroy(Chunk *chunk);
};
