// SPDX-License-Identifier: Zlib
// Copyright (C) 2024, Voxelius Contributors
#ifndef SHARED_CMAKE_HH_IN
#define SHARED_CMAKE_HH_IN

#define CMAKE_SYSTEM "Windows-10.0.19045"
#define CMAKE_SYSTEM_NAME "Windows"
#define CMAKE_SYSTEM_VERSION "10.0.19045"
#define CMAKE_SYSTEM_PROCESSOR "AMD64"

#define CMAKE_CXX_COMPILER_ID "MSVC"
#define CMAKE_CXX_COMPILER_VERSION "19.39.33523.0"
#define CMAKE_CXX_STANDARD 17

#define GAME_VERSION_STRING "Alpha 0.0.1"
#define GAME_VERSION_PROTOCOL 1

#endif /* SHARED_CMAKE_HH_IN */
